# Generated by Django 4.2.4 on 2023-08-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
