# Generated by Django 4.2.4 on 2023-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_register_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='updated_at',
        ),
    ]
